### ISSUE TITLE
where you get tutorial

### ISSUE THREAD

**Issue by mdestafadilah** [SafdarJamal/understanding-redux#11]
do you follow from video tutorial?

**Comment by SafdarJamal** [comment]
I started learning redux with this [article/book](https://www.freecodecamp.org/news/understanding-redux-the-worlds-easiest-guide-to-beginning-redux-c695f45546f6). But If you like video courses over written content, then check out this [tutorial](https://egghead.io/courses/getting-started-with-redux) by Dan Abramov. Both resources are free.

**Comment by mdestafadilah** [comment]
nice jamal. i follow your blog on css-tricks too. nice article about react.
